// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using UserManager.Web.Data;

namespace UserManager.Web.Migrations
{
    [DbContext(typeof(UserContext))]
    partial class UserContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.0.1");

            modelBuilder.Entity("UserManager.Web.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CustCode")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasMaxLength(50);

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasMaxLength(50);

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasMaxLength(20);

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasMaxLength(20);

                    b.HasKey("Id");

                    b.ToTable("User");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CustCode = "rogerwaters19500315",
                            DateOfBirth = new DateTime(1950, 3, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "rwaters@floydmail.com",
                            FirstName = "Roger",
                            LastName = "Waters"
                        },
                        new
                        {
                            Id = 2,
                            CustCode = "davidgilmour19550812",
                            DateOfBirth = new DateTime(1955, 8, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "dgilmour@floydmail.com",
                            FirstName = "David",
                            LastName = "Gilmour"
                        },
                        new
                        {
                            Id = 3,
                            CustCode = "nickmason19521101",
                            DateOfBirth = new DateTime(1952, 11, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "nmason@floydmail.com",
                            FirstName = "Nick",
                            LastName = "Mason"
                        },
                        new
                        {
                            Id = 4,
                            CustCode = "richardwright19570810",
                            DateOfBirth = new DateTime(1957, 8, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "rwright@floydmail.com",
                            FirstName = "Richard",
                            LastName = "Wright"
                        },
                        new
                        {
                            Id = 5,
                            CustCode = "sydbarrett19540222",
                            DateOfBirth = new DateTime(1954, 2, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "sbarrett@floydmail.com",
                            FirstName = "Syd",
                            LastName = "Barrett"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
